#%RAML 1.0
title: Kafka System API
version: v1
baseUri: http://localhost:8999/global-kafka-sys-api
protocols: [HTTPS]


traits: !include traits/traits.raml

types:
  common-response: !include common/common-response.raml
  lead-request: !include types/lead-request.raml
  error-response: !include common/common-response.raml

/lead:
  displayName: Lead
  is: [authorized]
  description: This endpoint allows to post data related to Lead from Salesforce Cloud.
  post:
    body:
      application/json:
        type: lead-request

    responses:
      201:
        body:
          application/json:
            type: common-response
            example: !include examples/responses/success-response.json

      400:
        body:
          application/json:
            type: error-response
            example: !include examples/responses/error-response-400.json