name: Publish GH Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  release:

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v10
        with:
          repositories: '[{ "id": "mulesoft-public", "url": "https://repository.mulesoft.org/nexus/content/repositories/public" },
                          { "id": "mule-releases", "url": "https://repository.mulesoft.org/releases" }]'

      - name: log-settings
        run: cat \/home\/runner\/.m2\/settings.xml

      - name: Build with Maven
        run: mvn --settings /home/runner/.m2/settings.xml clean install --file pom.xml

      - name: Guess Release Version
        run: |
          echo "RELEASE_VERSION=$(echo '${{github.ref}}' | sed -e 's,.*/v\(.*\),\1,')" >> $GITHUB_ENV

      #GH RELEASE
      - name: Create Release
        id: create_release

        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Asset tgz
        id: upload-release-asset-tgz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./runner/target/mule-migration-assistant-runner-${{env.RELEASE_VERSION}}.tar.gz
          asset_name: mule-migration-assistant-runner-${{env.RELEASE_VERSION}}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset tgz sha256
        id: upload-release-asset-tgz-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./runner/target/mule-migration-assistant-runner-${{env.RELEASE_VERSION}}.tar.gz.sha256
          asset_name: mule-migration-assistant-runner-${{env.RELEASE_VERSION}}.tar.gz.sha256
          asset_content_type: text/plain

      - name: Upload Release Asset zip
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./runner/target/mule-migration-assistant-runner-${{env.RELEASE_VERSION}}.zip
          asset_name: mule-migration-assistant-runner-${{env.RELEASE_VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset zip sha256
        id: upload-release-asset-zip-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./runner/target/mule-migration-assistant-runner-${{env.RELEASE_VERSION}}.zip.sha256
          asset_name: mule-migration-assistant-runner-${{env.RELEASE_VERSION}}.zip.sha256
          asset_content_type: text/plain
